name: Boostsecurity.io Scanner
description: Scans a repository for vulnerabilities
author: https://www.boostsecurity.io
requirements:
  - bash
  - docker
  - mktemp
configuration:
  properties:
    additional_args:
      description: "Additional CLI arguments to pass"
      type: string
    api_enabled:
      description: "Optional setting to enable offline mode"
      default: "true"
      enum: ["true", "false"]
      type: string
    api_endpoint:
      description: "Boost API endpoint"
      default: https://api.boostsecurity.io
      type: string
    api_token:
      description: "Boost API token"
      type: string
    cli_version:
      description: "Scanner version"
      default: "1"
      type: string
    ignore_failure:
      description: "Ignore any exception returned by the scanner cli"
      default: "false"
      enum: ["true", "false"]
      type: string
    log_level:
      description: "Set the cli logging level"
      enum: ["TRACE", "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]
      type: string
    main_branch:
      description: "Optional override for main branch detection"
      type: string
    pre_scan_cmd:
      description: "Optional command to run before scanning"
      type: string
    registry_module:
      description: "Module within the scanner registry to execute"
      type: string
    scanner_id:
      description: "Optional identifier to uniquely identify the scanner"
      type: string
    scan_label:
      description: "Optional identifier to identify a a monorepo component"
      type: string
    scan_timeout:
      description: "Maximum amount of time a diff scan should complete in"
      type: integer
  additionalProperties: false
